language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file_glob: true
    file: dist/*.whl
    skip_cleanup: true
    draft: true
    on:
        tags: true

matrix:
  include:
    - os: linux
      dist: xenial
    - os: windows
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
      os: osx
      osx_image: xcode9.4
      compiler: clang

install:
  - python -m pip install -U setuptools wheel pip

script:
  - python setup.py bdist_wheel
