language: python
python:
    - "3.6"

deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file_glob: true
    file: dist/*.whl
    skip_cleanup: true
    draft: true
    on:
        tags: true

matrix:
  include:
    - os: linux
      dist: xenial
    - os: windows
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
      os: osx
      osx_image: xcode9.4
      compiler: clang

install:
  # ensure recent versions of setuptools
  - python -m pip install -U setuptools wheel pip

script:
  # test if we can still build
  - python setup.py bdist_wheel
  # install in development-mode
  - python setup.py develop
  # tests
  - python -c 'import wgpu'  # stub
